#!/bin/bash

MANIFEST=https://github.com/Evolution-X/manifest.git
BRANCH=elle
DEVICE=dipper
BRAND=xiaomi
PLATFORM=sdm845
DT_LINK=https://github.com/Evolution-X-Devices/device_xiaomi_dipper
CT_LINK=https://github.com/MemeGang-Development/device_xiaomi_sdm845-common
DVT_LINK=https://github.com/MemeGang-Development/vendor_xiaomi_dipper
CVT_LINK=https://github.com/MemeGang-Development/vendor_xiaomi_sdm845-common
KT_LINK=https://github.com/MemeGang-Development/kernel_xiaomi_polaris

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name DarkAngelGR
git config --global user.email asavvo01@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

git clone $DT_LINK --single-branch -b elle device/$BRAND/$DEVICE
git clone $CT_LINK --singel-branch -b no-thermal device/xiaomi/sdm845-common
git clone $VT_LINK --single-branch -b eleven vendor/$BRAND/$DEVICE
git clone $KT_LINK --single-branch -b no-thermal kernel/$BRAND/$DEVICE
git clone $CVT_LINK --single-branch -b eleven vendor/$BRAND/sdm845-common
